cxx_python_extension(
    name = "c_ext",
    srcs = ["ext.c"],
    visibility = ["PUBLIC"],
    base_module = "",
    # TODO: this should come from the python toolchain
    preprocessor_flags=["-I$(location toolchains//:cpython_archive[include])"],
)
